# Generated by Django 4.1.2 on 2022-10-14 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_book_delete_choice_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='stock',
            field=models.PositiveBigIntegerField(),
        ),
    ]
